-- MySQL Script generated by MySQL Workbench
-- Thu Feb  1 11:15:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories` ;

CREATE TABLE IF NOT EXISTS `categories` (
                                            `id` INT NOT NULL,
                                            `title` VARCHAR(45) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tva` ;

CREATE TABLE IF NOT EXISTS `tva` (
                                     `id` INT NOT NULL,
                                     `tva` DOUBLE NULL,
                                     PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products` ;

CREATE TABLE IF NOT EXISTS `products` (
                                          `id` INT NOT NULL,
                                          `title` VARCHAR(45) NULL,
    `description` LONGTEXT NULL,
    `priceTTC` FLOAT NULL,
    `weight` INT NULL,
    `tva` INT NULL,
    `stock` INT NULL,
    `categories_id` INT NOT NULL,
    `tva_id` INT NOT NULL,
    `price_HTT` FLOAT NULL,
    PRIMARY KEY (`id`, `tva_id`),
    INDEX `fk_products_categories_idx` (`categories_id` ASC) VISIBLE,
    INDEX `fk_products_tva1_idx` (`tva_id` ASC) VISIBLE,
    CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_products_tva1`
    FOREIGN KEY (`tva_id`)
    REFERENCES `tva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clients` ;

CREATE TABLE IF NOT EXISTS `clients` (
                                         `id` INT NOT NULL,
                                         `first_name` VARCHAR(45) NULL,
    `last_name` VARCHAR(45) NULL,
    `email` VARCHAR(45) NULL,
    `password` VARCHAR(45) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order` ;

CREATE TABLE IF NOT EXISTS `order` (
                                       `id` INT NOT NULL,
                                       `number` INT NULL,
                                       `order_date` DATE NULL,
                                       `ship_date` DATE NULL,
                                       `clients_id` INT NOT NULL,
                                       PRIMARY KEY (`id`),
    INDEX `fk_order_clients1_idx` (`clients_id` ASC) VISIBLE,
    CONSTRAINT `fk_order_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `products_has_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `products_has_order` ;

CREATE TABLE IF NOT EXISTS `products_has_order` (
                                                    `products_id` INT NOT NULL,
                                                    `order_id` INT NOT NULL,
                                                    `amount` INT NULL,
                                                    PRIMARY KEY (`order_id`, `products_id`),
    INDEX `fk_products_has_order_order1_idx` (`order_id` ASC) VISIBLE,
    INDEX `fk_products_has_order_products1_idx` (`products_id` ASC) VISIBLE,
    CONSTRAINT `fk_products_has_order_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_products_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;